TEAM_NAME_CLASS = 'club-name'
TEAM_LOGO_CLASS = 'club-logo'
MATCH_RESULT_CLASS = 'column-score'
MATCH_PLAN_SECTION_NAME = 'matchplan'
MATCHES_SECTION_NAME = 'matches'
MATCH_PLAN_URL_PREFIX = 'spielplan'
MATCHES_URL_PREFIX = 'spieltagsuebersicht'
SECTION_DIVIDER = 'section/'
